
sudo: true
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install -g react-starter-cli

script:
  - jreact init demo -y
  - cd demo
  - npm install
  - npm test