
sudo: true
language: node_js
node_js:
  - "7"

cache:
  directories:
    - node_modules

install:
  - npm install -g react-starter-cli

script:
  - jreact init react-demo
  - cd react-demo
  - npm install
  - npm test