
sudo: true
language: node_js
node_js:
  - "7"

cache:
  directories:
    - node_modules

install:
  - npm install -g yo
  - npm install -g generator-jreact

script:
  - mkdir home/travis/react-dmeo
  - cd home/travis/react-demo
  - yo jreact
  - npm test